train_selfsup_8cams:
    name: [Tractor]
    path: [/data/vidar/GreenTractor/GreenTractor.json]
    split: [train]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: [-1,1]
    labels: []
    cameras: [[1],[2],[3],[4],[5],[6],[7],[8]]
    repeat: [100]
validation_8cams:
    name: [Tractor]
    path: [/data/vidar/GreenTractor/GreenTractor.json]
    split: [val]
    augmentation:
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    labels: []
    cameras: [[1],[2],[3],[4],[5],[6],[7],[8]]
display_results:
    name: [Tractor]
    path: [/data/vidar/GreenTractor/GreenTractor.json]
    split: [val]
    augmentation:
        resize: [384, 640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 16
    context: []
    cameras: [[1,2,3,4,5,6,7,8]]
    labels: [pose]
    labels_context: [pose]
    virtual: [False]

