wrapper:
    recipe: wrapper|default
arch:
    model:
        file: depth/FSMModel
        checkpoint: /data/vidar/models/papers/final/FSM_MR_6cams_DDAD.ckpt
    networks:
        depth:
            recipe: networks/focal_depth_res_net|fsm_ddad
        pose:
            recipe: networks/conv_pose_net|default
evaluation:
    depth:
        recipe: evaluation/depth|ddad_resize
datasets:
    validation:
        recipe: datasets/green_tractor|display_results
save:
    recipe: save|green_tractor_undist
display:
    start: 0
    stop: 4000
