
# To download datasets use the following command:
# wget https://tri-ml-public.s3.amazonaws.com/github/vidar/datasets/{DATASET}.tar /data/vidar
# Don't forget to untar it afterwards, with:
# tar xvf /data/vidar/{DATASET}.tar -C /data/vidar

datasets:
    ddad:
        name: [Ouroboros]
        path: [/data/vidar/DDAD/ddad.json]
        split: [train]
        context: [-1,2]
        cameras: [[1,5,6,7,8,9]]
        labels: [depth,pose]
        labels_context: [depth,pose]
        depth_type: [lidar]
        virtual: [False]